#pragma once

#define CD_OPERATION "cd"
#define EXIT_OPERATION "exit"
#define FG_OPERATOR "%"
#define COMMAND_DELIMITER "<3"
#define WORD_DELIMITER " "
#define MAX_COMMANDS_PER_COMMANDLINE 5
#define MAX_OPTIONS 3
#define MAX_SESSIONS 64
#define COMMANDLINE_BUFFER_SIZE 1000
